# Generated by Django 5.0.6 on 2024-06-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='anu', max_length=30, verbose_name='enter ur first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='enter ur last name')),
                ('email', models.EmailField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_emp',
            },
        ),
    ]
